"""Canonical worker boundary."""

# Re-export queue naming, serialization, and concurrency primitives from core.
from ..core.worker.concurrency import (
    ALL_PROFILES,
    PROFILE_DEFAULT,
    PROFILE_EMAIL,
    PROFILE_INTEGRATION_SYNC,
    PROFILE_REPORTS,
    PROFILE_SCHEDULED,
    PROFILE_WEBHOOK_INGEST,
    QueueConcurrencyProfile,
)
from ..core.worker.dead_letter import (
    JOB_DEAD_LETTER_NAMESPACE,
    JobDeadLetterRequest,
    JobDeadLetterResult,
    JobDeadLetterStore,
    build_dead_letter_request_from_job,
    job_dead_letter_store,
)
from ..core.worker.queue_naming import (
    DEFAULT_QUEUE_NAME,
    RESERVED_SCOPES,
    QueueNameError,
    QueueNamespace,
    client_queues,
    integration_queues,
    is_reserved_scope,
    platform_queues,
    validate_queue_name,
    webhook_queues,
)
from ..core.worker.replay import (
    ReplayRequest,
    ReplayResult,
    build_replay_request_from_dead_letter,
    replay_dead_lettered_job,
)
from ..core.worker.retry import (
    BACKOFF_FAST,
    BACKOFF_SLOW,
    BACKOFF_STANDARD,
    NON_RETRYABLE_CATEGORIES,
    BackoffPolicy,
    JobAlertHook,
    JobFailureCategory,
    LoggingAlertHook,
    is_retryable_category,
)
from ..core.worker.serialization import (
    JobPayloadSerializationError,
    safe_payload,
    serialize_for_envelope,
    validate_json_safe,
)
from .jobs import (
    JobEnvelope,
    JobRetryPolicy,
    JobTenantContext,
    NonRetryableJobError,
    RetryableJobError,
    WorkerProbeJob,
    worker_functions,
    worker_probe_job,
)
from .logging import (
    DEFAULT_JOB_LOGGER_NAME,
    JOB_LOG_CONTEXT_KEYS,
    bind_job_log_context,
    build_job_log_context,
    clear_job_log_context,
    get_job_logger,
)
from .settings import WorkerSettings, start_arq_service, start_worker

__all__ = [
    "ALL_PROFILES",
    "BACKOFF_FAST",
    "BACKOFF_SLOW",
    "BACKOFF_STANDARD",
    "BackoffPolicy",
    "DEFAULT_JOB_LOGGER_NAME",
    "DEFAULT_QUEUE_NAME",
    "JOB_DEAD_LETTER_NAMESPACE",
    "JOB_LOG_CONTEXT_KEYS",
    "JobAlertHook",
    "JobDeadLetterRequest",
    "JobDeadLetterResult",
    "JobDeadLetterStore",
    "JobEnvelope",
    "JobFailureCategory",
    "JobPayloadSerializationError",
    "JobRetryPolicy",
    "JobTenantContext",
    "LoggingAlertHook",
    "NON_RETRYABLE_CATEGORIES",
    "NonRetryableJobError",
    "PROFILE_DEFAULT",
    "PROFILE_EMAIL",
    "PROFILE_INTEGRATION_SYNC",
    "PROFILE_REPORTS",
    "PROFILE_SCHEDULED",
    "PROFILE_WEBHOOK_INGEST",
    "QueueConcurrencyProfile",
    "QueueNameError",
    "QueueNamespace",
    "RESERVED_SCOPES",
    "ReplayRequest",
    "ReplayResult",
    "RetryableJobError",
    "WorkerProbeJob",
    "WorkerSettings",
    "bind_job_log_context",
    "build_dead_letter_request_from_job",
    "build_job_log_context",
    "build_replay_request_from_dead_letter",
    "clear_job_log_context",
    "client_queues",
    "get_job_logger",
    "integration_queues",
    "is_reserved_scope",
    "is_retryable_category",
    "job_dead_letter_store",
    "on_job_end",
    "on_job_start",
    "platform_queues",
    "replay_dead_lettered_job",
    "safe_payload",
    "serialize_for_envelope",
    "start_arq_service",
    "start_worker",
    "validate_json_safe",
    "validate_queue_name",
    "webhook_queues",
    "worker_functions",
    "worker_probe_job",
]
