"""Canonical authorization surface."""

from ..core.authorization import (
    ADMIN_ROLE,
    AUTHENTICATED_ROLE,
    DEFAULT_AUTHORIZATION_POLICY,
    DEFAULT_PERMISSION_DENIED_MESSAGE,
    DEFAULT_PERMISSION_POLICY,
    DEFAULT_ROLE_PERMISSION_GRANTS,
    SUPERUSER_ROLE,
    WILDCARD_PERMISSION,
    AuthorizationSubject,
    Permission,
    PermissionPolicy,
    RolePermissionPolicy,
    TemplatePermission,
    TemplateRole,
    authorize_owner_or_permission,
    authorize_permission,
    build_authorization_subject,
    ensure_permissions,
    ensure_roles,
    has_permission,
    is_resource_owner,
    subject_has_role,
)

__all__ = [
    "ADMIN_ROLE",
    "AUTHENTICATED_ROLE",
    "AuthorizationSubject",
    "DEFAULT_AUTHORIZATION_POLICY",
    "DEFAULT_PERMISSION_DENIED_MESSAGE",
    "DEFAULT_PERMISSION_POLICY",
    "DEFAULT_ROLE_PERMISSION_GRANTS",
    "Permission",
    "PermissionPolicy",
    "RolePermissionPolicy",
    "SUPERUSER_ROLE",
    "TemplatePermission",
    "TemplateRole",
    "WILDCARD_PERMISSION",
    "authorize_owner_or_permission",
    "authorize_permission",
    "build_authorization_subject",
    "ensure_permissions",
    "ensure_roles",
    "has_permission",
    "is_resource_owner",
    "subject_has_role",
]
