"""Canonical authentication and security surface."""

from ..core.security import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    ALGORITHM,
    JWT_ACTIVE_KEY_ID,
    JWT_AUDIENCE,
    JWT_ISSUER,
    REFRESH_TOKEN_EXPIRE_DAYS,
    SECRET_KEY,
    TokenType,
    authenticate_user,
    blacklist_token,
    blacklist_tokens,
    build_api_key_auth_headers,
    build_refresh_token_cookie_delete_kwargs,
    build_refresh_token_cookie_kwargs,
    clear_refresh_token_cookie,
    create_access_token,
    create_refresh_token,
    get_password_hash,
    oauth2_scheme,
    password_hash_needs_rehash,
    resolve_api_key_principal,
    rotate_refresh_token,
    set_refresh_token_cookie,
    verify_password,
    verify_token,
)

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "ALGORITHM",
    "JWT_ACTIVE_KEY_ID",
    "JWT_AUDIENCE",
    "JWT_ISSUER",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    "SECRET_KEY",
    "TokenType",
    "authenticate_user",
    "blacklist_token",
    "blacklist_tokens",
    "build_api_key_auth_headers",
    "build_refresh_token_cookie_delete_kwargs",
    "build_refresh_token_cookie_kwargs",
    "clear_refresh_token_cookie",
    "create_access_token",
    "create_refresh_token",
    "get_password_hash",
    "oauth2_scheme",
    "password_hash_needs_rehash",
    "resolve_api_key_principal",
    "rotate_refresh_token",
    "set_refresh_token_cookie",
    "verify_password",
    "verify_token",
]
